// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vault} from '../models';
import {config} from '../models';

export function APIState():Promise<main.APIStatus>;

export function AddAllowlistEntry(arg1:string):Promise<void>;

export function AddCategory(arg1:string):Promise<vault.Category>;

export function AuditLog():Promise<Array<vault.AuditEntry>>;

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function CopySecretField(arg1:string,arg2:string):Promise<void>;

export function CreateVault(arg1:string,arg2:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteSecret(arg1:string):Promise<void>;

export function ExportVault():Promise<string>;

export function GeneratePassword(arg1:number,arg2:boolean):Promise<string>;

export function GetAPIKey():Promise<string>;

export function GetSecret(arg1:string):Promise<vault.Secret>;

export function GetSettings():Promise<config.Config>;

export function ImportVault():Promise<number>;

export function IsUnlocked():Promise<boolean>;

export function LastVault():Promise<string>;

export function ListCategories():Promise<Array<vault.Category>>;

export function ListSecrets(arg1:string):Promise<Array<vault.Secret>>;

export function LockVault():Promise<void>;

export function RemoveAllowlistEntry(arg1:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function RotateAPIKey():Promise<string>;

export function SaveSecret(arg1:string,arg2:vault.SecretInput):Promise<vault.Secret>;

export function SelectVaultToCreate():Promise<string>;

export function SelectVaultToOpen():Promise<string>;

export function SetAPIAutoStart(arg1:boolean):Promise<void>;

export function SetAutoLock(arg1:boolean,arg2:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ToggleServer():Promise<main.APIStatus>;

export function UIAck(arg1:string,arg2:string):Promise<void>;

export function UnlockVault(arg1:string,arg2:string):Promise<void>;

export function Version():Promise<string>;
