// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIState() {
  return window['go']['main']['App']['APIState']();
}

export function AddAllowlistEntry(arg1) {
  return window['go']['main']['App']['AddAllowlistEntry'](arg1);
}

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AuditLog() {
  return window['go']['main']['App']['AuditLog']();
}

export function CategoryPalette() {
  return window['go']['main']['App']['CategoryPalette']();
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CopySecretField(arg1, arg2) {
  return window['go']['main']['App']['CopySecretField'](arg1, arg2);
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function ExportVault() {
  return window['go']['main']['App']['ExportVault']();
}

export function GeneratePassword(arg1, arg2) {
  return window['go']['main']['App']['GeneratePassword'](arg1, arg2);
}

export function GetAPIStatus() {
  return window['go']['main']['App']['GetAPIStatus']();
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function ImportVault() {
  return window['go']['main']['App']['ImportVault']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function LastVault() {
  return window['go']['main']['App']['LastVault']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function RecentVaults() {
  return window['go']['main']['App']['RecentVaults']();
}

export function RemindUpdateLater() {
  return window['go']['main']['App']['RemindUpdateLater']();
}

export function RemoveAllowlistEntry(arg1) {
  return window['go']['main']['App']['RemoveAllowlistEntry'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RotateAPIKey() {
  return window['go']['main']['App']['RotateAPIKey']();
}

export function SaveSecret(arg1, arg2) {
  return window['go']['main']['App']['SaveSecret'](arg1, arg2);
}

export function SelectVaultToCreate() {
  return window['go']['main']['App']['SelectVaultToCreate']();
}

export function SelectVaultToOpen() {
  return window['go']['main']['App']['SelectVaultToOpen']();
}

export function SetAPIAutoStart(arg1) {
  return window['go']['main']['App']['SetAPIAutoStart'](arg1);
}

export function SetAutoLock(arg1, arg2) {
  return window['go']['main']['App']['SetAutoLock'](arg1, arg2);
}

export function SetCategoryColor(arg1, arg2) {
  return window['go']['main']['App']['SetCategoryColor'](arg1, arg2);
}

export function SetHTTPS(arg1) {
  return window['go']['main']['App']['SetHTTPS'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetToastSeconds(arg1) {
  return window['go']['main']['App']['SetToastSeconds'](arg1);
}

export function SetUpdateAutoCheck(arg1) {
  return window['go']['main']['App']['SetUpdateAutoCheck'](arg1);
}

export function SetZoom(arg1) {
  return window['go']['main']['App']['SetZoom'](arg1);
}

export function ShuffleAPIPort() {
  return window['go']['main']['App']['ShuffleAPIPort']();
}

export function SkipUpdateVersion() {
  return window['go']['main']['App']['SkipUpdateVersion']();
}

export function StartAPIServer() {
  return window['go']['main']['App']['StartAPIServer']();
}

export function StopAPIServer() {
  return window['go']['main']['App']['StopAPIServer']();
}

export function UIAck(arg1, arg2) {
  return window['go']['main']['App']['UIAck'](arg1, arg2);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['main']['App']['UnlockVault'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
