// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIState() {
  return window['go']['main']['App']['APIState']();
}

export function AddAllowlistEntry(arg1) {
  return window['go']['main']['App']['AddAllowlistEntry'](arg1);
}

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AuditLog() {
  return window['go']['main']['App']['AuditLog']();
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function CopySecretField(arg1, arg2) {
  return window['go']['main']['App']['CopySecretField'](arg1, arg2);
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function ExportVault() {
  return window['go']['main']['App']['ExportVault']();
}

export function GeneratePassword(arg1, arg2) {
  return window['go']['main']['App']['GeneratePassword'](arg1, arg2);
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportVault() {
  return window['go']['main']['App']['ImportVault']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function LastVault() {
  return window['go']['main']['App']['LastVault']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function RemoveAllowlistEntry(arg1) {
  return window['go']['main']['App']['RemoveAllowlistEntry'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RotateAPIKey() {
  return window['go']['main']['App']['RotateAPIKey']();
}

export function SaveSecret(arg1, arg2) {
  return window['go']['main']['App']['SaveSecret'](arg1, arg2);
}

export function SelectVaultToCreate() {
  return window['go']['main']['App']['SelectVaultToCreate']();
}

export function SelectVaultToOpen() {
  return window['go']['main']['App']['SelectVaultToOpen']();
}

export function SetAPIAutoStart(arg1) {
  return window['go']['main']['App']['SetAPIAutoStart'](arg1);
}

export function SetAutoLock(arg1, arg2) {
  return window['go']['main']['App']['SetAutoLock'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ToggleServer() {
  return window['go']['main']['App']['ToggleServer']();
}

export function UIAck(arg1, arg2) {
  return window['go']['main']['App']['UIAck'](arg1, arg2);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['main']['App']['UnlockVault'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
